### PR TITLE
Unit tests for eg 44 and eg63

### PR DESCRIPTION
**Pull request by acatlett8**
This is a combination of EG-44 and EG-63 Jira tasks.
Need of @CannedIce  double check:

- to test calc_canopy_area_from_shoot_width i needed to add a duration parameter of senesce_rate. Please make sure this number is accurate or please advise on a better way to do that. 

Big overall changes:

- added a check objects file with UnitTestChecks class that will hold common tests that i've noticed will be needed throughout the species class (so far only one method)
- removed any shape file or classes

 @CannedIce the only thing i would like your input on is i added duration param - senesce_rate (where i just got a random number from running the notebook). Is this a good number?? 

- [ X] Add / update tests if necessary?
- [X ] All tests have passed?
- [ X] Formatted code with black?
- [ X] Removed lint reported by flake8?

### CODE REVIEW

**Comment by CannedIce** [comment]
The senesce rate is calculated as part of the species initialization. It is calculated as 0.9(growing_season_end - senesce_start) and represents an assumption that 90% of the carbohydrate from the plant green parts (like the leaves) moves to the persistent parts (like the roots) over the senescence period. I'm not sure how best to represent that in the unit test since it is a dependency on the calculate_derived_params method in the Species class. We could run the calculate_derived_params method as part of the unit test. I'm open to discuss what makes the most sense.

**Comment by acatlett8** [comment]
Probably means i should have done the unit tests for calculate_derived_params first. I've started working on this unit test method. but i do think that your suggestion to call calculate_derived_params is good. i'll implement that!

**Comment by acatlett8** [comment]
I'm guessing that pytest can update example_input_param. I just initialized the species class in each of my testing methods and it worked..... i'm not sure. but it works???

**Comment by CannedIce** [comment]
That makes sense that initializing the Species class worked because as part of the initialization it runs calculate_derived_params and calculate the senesce rate. I'll look at the unit tests and merge. Thanks for sticking to this and figuring it out.

**Pull request merged**
